version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: sqlite:///app.db
    volumes:
      - .:/app
      - /app/__pycache__
      - /instance

volumes:
  db_data:


